name: Test GHA

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Build dist Directory
        id: build
        run: npm run bundle

      - name: What?
        id: what
        run: ls -al

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          file: '../phrase-report.json'
